### ISSUE TITLE
Example function fails when running testcheck installed from npm, works when testcheck built from source

### ISSUE THREAD

**Issue by utanapishtim** [leebyron/testcheck-js#31]
Ubuntu: 16.04, 4.9 kernel 
Node: v6.9.2
installed testcheck-js via: npm install --save-dev testcheck
opened node repl in shell, then ran
```
const { check, property, gen } = require('testcheck')

check(property(gen.int, (x) => x - x === 0))
```
Got the following error:
```
node_modules/testcheck/dist/testcheck.js:280

function Ig(a,b){var c=oc(b)?T.a(ze,b):b,d=Yb.a(c,Rf);return Fg(function(b,c,d){return function(b,c){return a.b?a.b(d.a?d.a(b,c):d.call(null,b,c)):a.call(null,d.a?d.a(b,c):d.call(null,b,c))}}(b,c,d))}function Jg(a,b){var c=oc(a)?T.a(ze,a):a,d=Yb.a(c,Rf);return Fg(function(a,c,d){return function(a,c){var e=d.a?d.a(a,c):d.call(null,a,c),e=b.b?b.b(e):b.call(null,e),e=oc(e)?T.a(ze,e):e,e=Yb.a(e,Rf);return e.a?e.a(a,c):e.call(null,a,c)}}(a,c,d))}function Kg(a,b){return Ig(ed.a(ug,a),b)}
                                                                                                                                                                   
TypeError: Cannot read property 'a' of null
    at node_modules/testcheck/dist/testcheck.js:280:309
    at node_modules/testcheck/dist/testcheck.js:280:421
    at node_modules/testcheck/dist/testcheck.js:280:323
    at node_modules/testcheck/dist/testcheck.js:280:323
    at node_modules/testcheck/dist/testcheck.js:279:400)
    at Function.b (node_modules/testcheck/dist/testcheck.js:290:615)
    at node_modules/testcheck/dist/testcheck.js:292:744
    ...
```
I cloned the repo and ran npm run build and everything works perfect, so it seems to be an issue with the npm package itself.

Please, let me know if there is any more info that would be useful.

**Comment by leebyron** [comment]
Yep sorry, going through some work towards a 1.0 release very soon. 

If you follow the instructions in the README that comes with the current npm package you'll have better luck.
