### ISSUE TITLE
gen.oneOf should ensure argument is an array

### ISSUE THREAD

**Issue by akiellor** [leebyron/testcheck-js#42]
Applying a constraint to `oneOf` to ensure the arguments are correct should provide the user with a friendly message when it has been used incorrectly, the current message leaks some of the implementation detail and not so intuitive.

```javascript
const ts = require("testcheck")
ts.sample(ts.gen.oneOf(ts.gen.posInt, ts.gen.numberWithin(0, 100)))

Error: [object Object] is not ISeqable
    at Error (native)
    at E (/usr/src/app/node_modules/testcheck/dist/testcheck.js:90:423)
    at /usr/src/app/node_modules/testcheck/dist/testcheck.js:210:56
    at Ce (/usr/src/app/node_modules/testcheck/dist/testcheck.js:160:54)
    at Be.h.Y (/usr/src/app/node_modules/testcheck/dist/testcheck.js:162:291)
    at E (/usr/src/app/node_modules/testcheck/dist/testcheck.js:90:313)
    at Xe (/usr/src/app/node_modules/testcheck/dist/testcheck.js:183:52)
    at to (/usr/src/app/node_modules/testcheck/dist/testcheck.js:442:143)
    at Object.exports.gen.oneOf (/usr/src/app/node_modules/testcheck/dist/testcheck.js:734:136)
    at repl:1:18
```

**Comment by akiellor** [comment]
When using flow this is not an issue, as the type checker picks this up.

Closing.
